name: CI

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, ubuntu-18.04, windows-latest]
        node: [14]
        
    name: 📦 Node ${{ matrix.node }} 🖥️ ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install
      
      - name: Build project
        run: yarn build